### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received WriteStream

### ISSUE THREAD

**Issue by realrecordzLab** [kzar/abp2chromerules#3]
I get this error when I try to create rules using [easylist](https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt)

Is there a fix? 
```
host:abp2chromerules-main lab$ node abp2chromerules.js /Users/lab/Desktop/adservers.txt
internal/streams/pipeline.js:61
    throw new ERR_INVALID_CALLBACK(streams[streams.length - 1]);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received WriteStream {
  connecting: false,
  _hadError: false,
  _parent: null,
  _host: null,
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: null,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    paused: true,
    emitClose: false,
    autoDestroy: false,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrain: 0,
    readingMore: false,
    decoder: null,
    encoding: null
  },
  readable: false,
  _events: [Object: null prototype] { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    bufferedRequest: null,
    lastBufferedRequest: null,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: false,
    bufferedRequestCount: 0,
    corkedRequestsFree: {
      next: null,
      entry: null,
      finish: [Function: bound onCorkedFinish]
    }
  },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server: null,
  _server: null,
  columns: 80,
  rows: 24,
  _type: 'tty',
  fd: 1,
  _isStdio: true,
  destroySoon: [Function: destroy],
  _destroy: [Function: dummyDestroy],
  [Symbol(asyncId)]: 3,
  [Symbol(kHandle)]: TTY { [Symbol(owner)]: [Circular] },
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0
}
    at popCallback (internal/streams/pipeline.js:61:11)
    at pipeline (internal/streams/pipeline.js:66:20)
    at Object.<anonymous> (/Users/lab/Desktop/abp2chromerules-main/abp2chromerules.js:68:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11

**Comment by kzar** [comment]
You're supposed to pipe the filter list's contents into the script, not provide the filter list's filename as an argument to it.

In other words try this:

    node abp2chromerules.js < /Users/lab/Desktop/adservers.txt

or this:

    cat /Users/lab/Desktop/adservers.txt | node abp2chromerules.js

Though having said that, I can't reproduce that error message myself. Which version of Node.js do you have?

**Comment by realrecordzLab** [comment]
ok, I was misunderstanding the documentations about. Anyway I'm using node
v12.4.0 , I will retry using your suggestion. thank you for the quick answer

Il giorno dom 30 ago 2020 alle ore 18:58 Dave Vandyke <
notifications@github.com> ha scritto:

**Comment by realrecordzLab** [comment]
Tried both way you have suggested but the error still remain.
I've tried with this command in my macOS terminal:
host:abp2chromerules-main lab$ node abp2chromerules.js <
/Users/lab/Desktop/adservers.txt
and with the second way you've suggested:

host:abp2chromerules-main lab$ cat /Users/lab/Desktop/adservers.txt | node
abp2chromerules.js

**Comment by kzar** [comment]
I've made a small change to the script, it seems like the optional callback argument to `stream.pipeline` might be mandatory in newer versions of Node.js. Please could you pull that change and give the script another try?

**Comment by realrecordzLab** [comment]
> I've made a small change to the script, it seems like the optional callback argument to `stream.pipeline` might be mandatory in newer versions of Node.js. Please could you pull that change and give the script another try?

no problem, I will give it a try and let you know.

**Comment by realrecordzLab** [comment]
Tested the updated version, now after I press enter the script will return two square brackets 
```
[
]host:abp2chromerules-main lab$node abp2chromerules.js < /Users/lab/Desktop/adservers.txt
```
The original file become a blank document and all the content is lost. I think there is another little problem to fix

**Comment by realrecordzLab** [comment]
on macOS works fine using this command 
```
host:abp2chromerules-main lab$ cat /Users/lab/Desktop/adservers.txt | node abp2chromerules.js > output.txt
```

**Comment by kzar** [comment]
Great OK, I'll consider this fixed then. Thanks for reporting the problem!

**Comment by realrecordzLab** [comment]
You are welcome! This tool is very useful and I feel will become a must
have when manifest v3 will be introduced. Thank you for this great job!
If you want, we can collaborate in future.
Cheers

Il giorno mar 1 set 2020 alle ore 18:45 Dave Vandyke <
notifications@github.com> ha scritto:
